services:
  mongo:
    image: mongo:3.4
    container_name: mongo
    ports:
      - "27020:27017"
    volumes:
      - mongo:/data
    environment:
        MONGO_INITDB_ROOT_USERNAME: bxit
        MONGO_INITDB_ROOT_PASSWORD: bxit
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: bxit
      ME_CONFIG_MONGODB_ADMINPASSWORD: bxit
      ME_CONFIG_MONGODB_SERVER: mongodb
volumes:
  mongo: {}